# -*- coding: utf-8 -*-
"""TripFilesPolygonFilter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15eePYyQh7kCay_qLmkU7qtHCv7UIO7WV
"""

import pandas as pd

trips1 = pd.read_csv("drive/MyDrive/Trenton MOVES/Trenton/2020_OriginPixel34021_1.csv")
trips2 = pd.read_csv("drive/MyDrive/Trenton MOVES/Trenton/2020_OriginPixel34021_2.csv")

trips = pd.concat([trips1, trips2])

trips = trips.reset_index(level=0)
trips['OFIPS'] = trips['OFIPS'].astype(int)
#trips = trips.sort_values(by=["index"])

trips

from shapely.geometry import Point, Polygon
coordsTrenton = [[-74.803222, 40.299740],[-74.741002, 40.273607], [-74.680370, 40.207433], [-74.789937, 40.166892], [-74.844197, 40.239590], [-74.864321, 40.286586]]
polyTrenton = Polygon(coordsTrenton)

trips

TrentonTrips = []
for i, row in enumerate (trips.iloc[:,7]):
  origin = Point([float(row), float(trips.iloc[i,8])])
  if origin.within(polyTrenton):
    TrentonTrips.append(trips.iloc[i])
TrentonTrips = pd.DataFrame(TrentonTrips)
TrentonTrips.to_csv("drive/MyDrive/Trenton MOVES/Trenton/TrentonTrips")
TrentonTrips